### PR TITLE
Deduct the cache figure from the memory usage percentage metric

### PR DESCRIPTION
**Pull request by chrisgilbert**
Currently the calculation for memory usage of a container/cgroup being returned to SignalFX includes the Linux page cache.  This is generally considered to be incorrect, and may lead people to chase phantom memory leaks in their application.  See some other applications where they have fixed the same problem:

https://github.com/moby/moby/issues/10824
https://github.com/aws/amazon-ecs-agent/issues/280

Here's a fix to correctly deduct the figure where it is available.

For a demonstration on why the current calculation is incorrect, you can run the following to see how I/O usage influences the overall memory usage in a cgroup:

```
docker run --rm -ti alpine
cat /sys/fs/cgroup/memory/memory.stat
cat /sys/fs/cgroup/memory/memory.usage_in_bytes
dd if=/dev/zero of=/tmp/myfile bs=1M count=100
cat /sys/fs/cgroup/memory/memory.stat
cat /sys/fs/cgroup/memory/memory.usage_in_bytes
```

You should see that the `usage_in_bytes` value rises by 100MB just from creating a 100MB file. That file hasn't been loaded into anonymous memory by an application, but because it's now in the page cache, the container memory usage is _appearing_ to be higher.  Deducting the cache figure in `memory.stat` from the `usage_in_bytes` shows that the genuine use of anonymous memory hasn't risen.

Because the kernel can evict page cache memory, this memory should not be considered "in use" by the container, and it is not very useful to measure it.

If the container asks for more memory from the OS, it will get it, and page cache will be evicted where required.  Also see https://www.linuxatemyram.com for more explanations of why the page cache generally uses most, or all free memory on the machine.

### CODE REVIEW

**Comment by keitwb** [comment]
Thanks for the patch.  The way it was originally calculated is also in certain cases useful, especially for applications that make heavy use of page caching as a performance optimization.  By knowing how much memory, including the page cache, the application is using you can answer the question "Could my application make effective use of more memory?".  Granted, there are other questions that come into play, such as the nature of reads/writes in the page cache, but knowing your relative usage to the limit including the page cache is part of that.  The way you have calculated it answers the question "How much more memory can my application reserve before exhaustion/crash?".  These are both valid questions, and arguably the second is the much more critical question from an ops/infrastructure perspective (which I am assuming you are coming from).  So I can see why you want to change it.

Honestly though, the main reason it was calculated that way to begin with was just because the Docker engine didn't emit the cache stats in older API versions.

However, we don't like changing the calculation of existing metrics unless it is just egregiously wrong to begin with.  There are too many people using the metric as is and the version of collectd plugins is not very easily controlled by end users.  If we were implementing this from scratch I would probably go with the formula you used here though since it is the more intuitive value.  I also don't like that it will behave significantly differently between older/newer Docker engines due to the presence/absence of the detailed memory stats.

Since the cache size metrics are getting emitted by default, you should be able to use the following formula on the backend to get the same thing:

`100 * (memory.usage.total - memory.stats.cache) / memory.usage.limit` (This is the same formula as your change)

I had to do an aggregating sum by `plugin_instance` to make the timeseries line up (you would need to aggregate by `host` as well if docker container names can overlap).  Would this work for you?

https://docs.docker.com/config/containers/runmetrics/#metrics-from-cgroups-memory-cpu-block-io is a more detailed explanation of those detailed memory stats getting emitted in case they are helpful.

**Comment by chrisgilbert** [comment]
Thanks @keitwb.  We will be able to fix this for our own purposes as you suggest.  I mainly created the patch as I felt like other people are probably chasing their tails over phantom memory leaks a lot too.

> The way it was originally calculated is also in certain cases useful, especially for applications that make heavy use of page caching as a performance optimization. By knowing how much memory, including the page cache, the application is using you can answer the question "Could my application make effective use of more memory?

You can't do that from this figure, because as an application developer you don't have control over page caching.  It's a kernel level feature to optimise filesytem access, rather than any sort of cache that applications use.  It ought not be accounted for in this way at all IMHO, but that's the way the kernel developers chose to expose it, for better or worse.

The signalFX metric now differs from what is seen when you run `docker stats` which uses the calculation I have here.  They chose not to change what was outputted by their API and just added extra detail, but they did change the output of their stats command, and the percentage that shows.  

Amazon also changed their cloudwatch percentage memory use metrics for ECS, presumably being in a similar situation as you with lots of customers using the old metrics.

It seems like knowing the page cache use for a container _could_ be useful (though I am struggling to think of when), but knowing it as part of an overall percentage usage of the cgroup isn't useful, since it then disguises your actual RSS memory use.

As an application developer I would like to know if my application is using more memory than before in the most recent release, and could be optimised, or I need to change my docker memory configuration to avoid running out of memory and having it terminated, but I don't feel I should care about what the OS is doing for filesystem access optimisation, since I have no control over that.

In a garbage collected application with a max heap size as large, or larger than the cgroup memory limit (e.g the -Xmx parameter for java, or .NET core in server mode), the tendency will be for the percentage to get close to 100% and then just hover there, assuming the runtime can see the cgroup memory limit properly.  That's what we see in our .NET core app, so we've now turned off the alerts around memory usage whilst we fix the metrics.  Memory use rises quickly when we have high activity, just from logging.  It would happen for any I/O at all though, so a for a database the figure would very quickly rise to 100% and stay there I presume.

I agree it shouldn't be a different calculation depending on the docker version though.  Would returning a new metric instead work better?

Up to you what you do of course, but I mostly submitted it to try to help others, as we've burnt days looking into a memory leak that doesn't really exist.

**Comment by keitwb** [comment]
I've though about this some more and I think how you've done it is best.  The plugin actually requires Docker API version 1.21+ and always uses the versioned 1.21 endpoints which should generally always include the cache info, so I think my hangup on the difference in behavior is largely a moot point.

I will just put a note in the next release warning about the change in behavior but given that `memory.percent` should only go *down* it at least shouldn't cause anybody's detectors to fire inadvertently.

Thanks!

**Comment by keitwb** [comment]
Also, if you are using the Smart Agent, I would recommend using the [docker-container-stats monitor](https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/docker-container-stats.md) (to which I will make the same modification to exclude cache memory).  It scales a lot better in terms of CPU usage with a lot of containers on a given host in a way that is very hard to do in this plugin given some constraints of python and collectd.

**Comment by chrisgilbert** [comment]
Thanks @keitwb !  Will we get this change automatically when we install the latest agent version, or do you have a release schedule for it?

**Comment by keitwb** [comment]
If you are using the new agent (Smart Agent) the change is already released if you are using the `docker-container-stats` monitor (the recommended one because it uses a lot less CPU at high container counts).  This python plugin has not been updated in the Smart Agent bundle yet, although https://github.com/signalfx/signalfx-agent/pull/478 will do that. We don't follow any release schedule but I'll release it as soon as that PR gets merged if you want to keep using the collectd Python docker plugin.

**Comment by chrisgilbert** [comment]
We are still using the collectd based plugins at the moment.  Thanks, I'll watch the PR then and take a look when it's released 👍

**Comment by keitwb** [comment]
Ok, Smart Agent version 3.8.2 is released and should v3.0.0 of this repo in it.

**Pull request merged**
