### PR TITLE
Support ECS.

### PR DESCRIPTION
**Pull request by cep21**
ECS exposes task information for docker containers on a metadata URL.  We can fetch
this URL and add the ECSTaskID and ECSContainerName for each task on the host.  These
dimensions are enough to link the docker name back to the ECS task

### CODE REVIEW

**Comment by keitwb** [comment]
@cep21 by any chance does ECS set any labels that have this information on the docker containers when it runs them?  I'm seeing a [PR that was merged on the ecs-agent](https://github.com/aws/amazon-ecs-agent/pull/89/files) that seems to imply that it is (although I haven't tested this on ECS itself to see).  They have the full task ARN instead of just the simple id but either should be sufficient for correlation purposes.  

If so, you can do this through the [`Dimension` config option to the plugin](https://github.com/signalfx/docker-collectd-plugin#extracting-additional-dimensions), which allows pulling out container labels if these are in fact available (e.g. `Dimension "ECSTaskARN" "inspect:Config.Labels['com.amazonaws.ecs.task-arn']"`.

Can you confirm about the labels in your particular ECS env?  If that won't work, we'll accept your changes here.

**Comment by cep21** [comment]
Oh interesting!  Let me see if I can pull that in.

**Comment by cep21** [comment]
How does the docker plugin work with lables that don't exist?  Should these be part of the default in https://github.com/signalfx/integrations/blob/master/collectd-docker/10-docker.conf

**Comment by cep21** [comment]
Trying to figure out the best way to integrate this into the collectd docker image.

**Comment by keitwb** [comment]
I'm pretty sure it ignores missing values with the `inspect:` syntax, but it would still produce a lot of needless checking for the vast majority of people who don't use ECS.  Putting it in the integrations repo's config would make it a part of the docker image of collectd, but I think you're probably better off extending the image or using the `COLLECTD_CONFIGS` envvar to the collectd-docker container (if this is even feasible with ECS), since I don't see this being mainstream enough to put in our default config.

**Comment by cep21** [comment]
I was able to make it work with a custom image.

I added
```
+    Dimension "ECSTaskARN" "inspect:Config.Labels['com.amazonaws.ecs.task-arn']"
+    Dimension "ECSContainerName" "inspect:Config.Labels['com.amazonaws.ecs.container-name']"
+    Dimension "ECSCluster" "inspect:Config.Labels['com.amazonaws.ecs.cluster']"
```

And had to comment out the Dockerfile copying the integration config

```
diff --git a/alpine/Dockerfile b/alpine/Dockerfile
index 96426c6..255c355 100644
--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -66,7 +66,8 @@ RUN apk update \
     # Extract the configuration file for docker-collectd-plugin
     && unzip /tmp/integrations.zip -d /tmp \
     # Move the managed config into place
-    && cp /tmp/integrations-master/collectd-docker/10-docker.conf /etc/collectd/managed_config/ \
+    # Use our own docker config
+#    && cp /tmp/integrations-master/collectd-docker/10-docker.conf /etc/collectd/managed_config/ \
     # Set correct permissions on startup script
     && cd /run \
     && rm -rf /tmp/*
```

**Comment by cep21** [comment]
The ECSTaskARN gets changed from a `/` to a `_` inside it, which means I have to also change my application code to do the same so I can correlate metrics by that dimension.

Otherwise it works great.  Thanks!

**Pull request closed without merging**
